### ISSUE TITLE
Include Bird avatars

### ISSUE THREAD

**Issue by mundschenk-at** [mundschenk-at/avatar-privacy#115]
After #16, @deevad has also created a [Bird avatar generator](https://www.peppercarrot.com/extras/html/2019_bird-generator/).

**Comment by Deevad** [comment]
Hey, I updated the project to also have the bitmap of the bird avatar in 70x70px; https://framagit.org/Deevad/cat-avatar-generator/ (I don't have a proper theme switcher yet, but you'll find the array/asset config on the README document). Thank you for reusing my little painterly avatars generators!

**Comment by mundschenk-at** [comment]
Thank you, @Deevad, for creating these wonderful avatar sets. 

As for the pixel size, I actually think 256x256 is a better size for todays hires displays, if you only provide a single size. For Avatar Privacy I've already set up code infrastructure to generate scaled versions of bitmapped avatars (similar to what Gravatar does when serving images). Therefore, I use 512x512 parts as the base for both Cat and Bird avatars. (Mainly to keep performance snappy during image generation.)

BTW, I also changed the background to be transparent. This might be something that could be interesting for your codebase?

**Comment by Deevad** [comment]
I would really like to propose multi size in the source; even with just a folder system and something cheap like switching the path to the target folder to change the res. Sure, higher resolution might looks better for profile picture or other needs. For comments on blog, I found 70x70 were really convenient (for minimizing bandwith) when 100 comments needs to load.

Transparent background are also nice; but they mean PNG; and it increase the fill weight. Same here; very good for a profile picture, but for displaying a thread of 100 avatar might get a big impact.

Anyway; I welcome all change to make it more modular and offer more choice in my repo. Thanks if you find time to backport the work you did!

**Comment by mundschenk-at** [comment]
> I would really like to propose multi size in the source; even with just a folder system and something cheap like switching the path to the target folder to change the res. Sure, higher resolution might looks better for profile picture or other needs. For comments on blog, I found 70x70 were really convenient (for minimizing bandwith) when 100 comments needs to load.

Yes, without the dynamic resizing in my plugin (which is kind of tied to WordPress, although it could be rewritten in plain PHP using the GD extension) that might be a bit hard for people on limited bandwidth connections.

> Transparent background are also nice; but they mean PNG; and it increase the fill weight. Same here; very good for a profile picture, but for displaying a thread of 100 avatar might get a big impact.

Mhm, I'm not sure I follow here. What's bad about PNG? Oh, you are using JPEG, I never noticed that before. At 64 pixels, the bird avatars with transparent background are about 6.9 KB. On my production site, I automatically also convert them to WEBP for browsers that support that format, which saves a few bytes. 

I don't have your code installed, what size are the JPEGs generated by GD?

> Anyway; I welcome all change to make it more modular and offer more choice in my repo. Thanks if you find time to backport the work you did!

**Comment by Deevad** [comment]
> the dynamic resizing in my plugin

Haa, dynamic resize! I better understand now why it is important for your implementation to start with the best quality. If the server can do this task and if this task is not too intensive for the CPU, that's a good solution to control the resolution. :+1: Here I tried to lower as I can the CPU task because with the high volume of visitor I have, my host often report me I'm exeeding CPU usage. That's why I streamlined all the source to 70x70px to just have GD stacking up the sprite as they are and output the compositing without doing much efforts to compute.

> what size are the JPEGs generated by GD?

The JPG on my server average between a range of 2.8Kb to 3.4Kb max for 70x70px and a white background. (eg. https://www.davidrevoy.com/article434/episode-1-potion-of-flight )

**Comment by mundschenk-at** [comment]
How long are you caching the composed images? Do you get so many comments by new people that CPU comes into play often? Honestly, it is not something I've been optimizing for at this point. I try to limit memory usage somewhat (and larger base image size severely increase the amount of memory needed). Have you profiled image composition?

I'll try to check this before the next release, I could cache the composed images in the base size if CPU usage is an issue.

**Edit:** Ah, after rereading your comment, I got it wrong the first time: Resizing is potentially CPU intensive, not image composition. I do it completely in memory to eliminate file system latency costs, but I'm running this on my own server, so CPU usage is not issue for myself (though haven't had any complaints in that direction on WP.org either). If the images are cached for a reasonably long time (I use 1 week by default), only comments using new names/email address should trigger new image creation, so I don't think that's an issue in practice unless you delete the whole cache directory and everything is regenerated in one swoop.

**Comment by Deevad** [comment]
yep, I have my server for Pepper&Carrot that went down when I released the catavatar standalone generator ( https://www.peppercarrot.com/extras/html/2016_cat-generator/index.php ) because it was reused directly by website linking the image.  I then became maybe over precocious about it. 

For the cache; I keep them infinitely once generated a first time. It weight around 30Mb for 8K of avatars last time I checked with the 70x70px jpegs.

I have not done CPU profiling; I just saw report of my host (OVH) with CPU usage graph and a top 10 table of php script the most demanding for CPU on server; the catavatar generator was in first place. I reported it on a blog post about optimisation, last year. A picture https://www.davidrevoy.com/data/images/lab/2018-09-09_screenshot_112336_neti.jpg from it.
