### ISSUE TITLE
Avatar Privacy conflicts with Webmention Avatar Handler

### ISSUE THREAD

**Issue by dshanske** [mundschenk-at/avatar-privacy#152]
Avatar Privacy hooks into pre_get_avatar_data at priority 10, webmentions hooks in at 30.  Webmentions adopted the former Semantic Linkbacks code that pulls an avatar url from a meta key. However, your code sends it's own URL through.

Want to discuss how the two can avoid conflict.

**Comment by dshanske** [comment]
Looking at your code, you take control even if there is no email address or user id and pass a URL.

**Comment by mundschenk-at** [comment]
@dshanske, so you are looking for an attachment ID in a comment meta when WordPress is looking for the avatar of a `WP_Comment`? Should the function not check [whether the object is actually a webmention](https://github.com/pfefferle/wordpress-webmention/blob/fa035a4d742d0240d3d7f93f68ba405d1b7ed8cc/includes/class-webmention-avatar-handler.php#L159) (instead of a regular comment)?

Since we are talking about a local file, I'd rather not serve the full image. I'd like to find a way to integrate more closely and serve a resized avatar. To do this, I'd need to be able to lookup a SHA256 hash value (as discussed in https://github.com/pfefferle/wordpress-semantic-linkbacks/issues/6), so it would need to be a two-way integration.

My suggestion is that I add methods/filters to add additional "avatar type" handlers during runtime and the Webmentions plugin adds the actual handler if it detects Avatar Privacy (I'd suggest `webmention` as the type).

**Comment by dshanske** [comment]
Semantic Linkbacks actually sets webmentions of a reply type to type comment. This is something that is planned to change in a future version, where replies would be set to type reply, and the protocol of webmention would be in a meta key. It is looking for a URL or an attachment id. As of now, only URLs are being stored. Having it check for an attachment id as well seemed a good future way of storing a possible sideloaded file.

**Comment by dshanske** [comment]
The simplest way to generate an SHA256 hash is for Avatar Privacy to check the avatar meta key, and if it exists and is a URL, hash the URL, which will create the unique key.

**Comment by mundschenk-at** [comment]
Sorry for the delay. I have not yet had time to think about it (will have in the next weeks, now that WordCamp Vienna is done).

**Comment by dshanske** [comment]
Wish I'd realized...I've been in Europe for the last few weeks on business. I might have come over for the weekend to attend.

**Comment by dshanske** [comment]
Any word on this issue?

**Comment by mundschenk-at** [comment]
I'm tackling it in conjunction with #164.

**Comment by mundschenk-at** [comment]
Update: Basically, for now it will use your solution, but slightly more conditional and further down in the execution path.

**Comment by mundschenk-at** [comment]
Partially fixed in #156.

**Comment by bekopharm** [comment]
Works for me. My facepiles started working again and I see no Gravatar requests in my network analytic tab :+1:
