### ISSUE TITLE
Fatal Error on Plugin Activation

### ISSUE THREAD

**Issue by unixtam** [mundschenk-at/avatar-privacy#5]
Hi there. Activating this plugin displays the following error:

`Fatal error: Cannot use isset() on the result of an expression (you can use "null !== expression" instead) in /wp-content/plugins/avatar-privacy/includes/avatar-privacy/components/class-images.php on line 330`

This is PHP 5.6.36

**Comment by mundschenk-at** [comment]
****, a PHP7ism has crept in. Sorry about that. Will be fixed ASAP.

**Comment by mundschenk-at** [comment]
Thank you for reporting the error message! I was wondering why people were apparently dropping out of using the plugin, but I totally missed the problem with `isset` and `const` array expressions during testing :(

**Comment by unixtam** [comment]
No problem, here is another one: On network activation after installation, there is a database error:

```
    DESCRIBE wp_avatar_privacy;
    Table 'wordpress2.wp_avatar_privacy' doesn't exist
```

**Comment by mundschenk-at** [comment]
That's actually intentional, in that the WordPress function [`dbDelta()`](https://developer.wordpress.org/reference/functions/dbdelta/) handles the table creation/upgrade. This error should not be visible except with something like Query Monitor (line 2204 in the linked code suppresses the error messages before calling `DESCRIBE`).

**Comment by unixtam** [comment]
Nevermind then.
