### ISSUE TITLE
Pretty Permalinks for User Avatars

### ISSUE THREAD

**Issue by dshanske** [mundschenk-at/avatar-privacy#80]
Optionally, allow for a redirect to retireve a user avatar when then avatar is publicly shared that survives even when the image is changed.

For example /avatar/username.png 

I wouldn't want this for my commenters, but for myself, I would want to share this.

This might be doable concurrently with #75

**Comment by mundschenk-at** [comment]
Do you need that URL to remain unchanging only or does it need to be pretty? Also, do you simply need a programmatical way to get it (for use in another plugin) or will it have to be integrated with `get_avatar` itself?

**Comment by dshanske** [comment]
Unchanging is fine.

**Comment by mundschenk-at** [comment]
I have been thinking about unifying the filepath, but that has a negative impact on file caching when using the static default icons (i.e. a visitor would have to download multiply copies of mystery person). It would also mean avatar image files would have to be cached per site in a multisite invironment, because the default avatar is a site-specific option.

**Comment by mundschenk-at** [comment]
Or are you only worried about the URL of an uploaded avatar changing? That will be stable unless I have a reason to change the nesting of the file path (to prevent too large number of files inside a simgle directory - but as it is two levels already, it should be sufficient at this point (except maybe to move all size variations to a single subdirectory ... mhm ...).

The URL within one of "types" of avatar images will be stable unless you change the site's salt or the users email address.

@dshanske, is that enough for your use case or would you need a constant URL across all kinds of avatars (gravatar, user uploaded, various default avatars)?

**Comment by mundschenk-at** [comment]
@dshanske, have you thought about this?

**Comment by dshanske** [comment]
It was more, every time I change my locally stored avatar, I have to change all links to it

**Comment by mundschenk-at** [comment]
Is this an actual issue or just theoretical? Because (except for image format changes, e.g. `.jpg` vs `.png`) the URL of an uploaded avatar should stay stable (if the mail address or salt don't change).

**Comment by dshanske** [comment]
I think I am explaining the problem poorly.

**Comment by mundschenk-at** [comment]
I am willing to listen, @dshanske, if you want to try again :-)

**Comment by dshanske** [comment]
I link to my Avatar. I change my Avatar. I break links. I don't want to break links.

**Comment by mundschenk-at** [comment]
What type of avatar are you using and what type are you changing it to? (Type here: `gravatar`, `user`, any of the default images `mystery`, `retro` etc.)

Because unless you change the type or the email address of the account, the links should not break.

**Comment by dshanske** [comment]
custom upload

**Comment by dshanske** [comment]
So, user

**Comment by dshanske** [comment]
It might be easier for me to write a gist that redirects a random URL to the results of get avatar

**Comment by mundschenk-at** [comment]
Can you show me an example how the URL changes when you upload a new custom user avatar? It should always be `https://<yoursite>/wp-content/uploads/avatar-privacy/user/<y>/<u>/<yourhash>.[png|jpg]`. It should only change under the following circumstances:
* Your domain name changes.
* Your email changes.
* You change the salt of your WordPress installation (using a filter hook).
* Your new avatar uses the other image format.

We can discount the first item,  so that leaves the other three. Changing the salt should change the URL, on purpose, so we can discount that as well. 

The URL depending on the image format is kind of awkward, I'm more ambivalent about the mail address. I'll think about a way to implement that feature in a clean and performant, but it probably won't be at the top of my list for some time. For the meantime, if you always use the same image format and don't change your account's associated mail address, the URL will remain stable.

**Comment by mundschenk-at** [comment]
@dshanske Do you want to try to explain the issue again?

**Comment by mundschenk-at** [comment]
Do you want to try again, @dshanske? I'm working on 2.3.0 (although it might end up as 3.0.0 instead), so if I understand what's needed, I'd like to close this one off.

**Comment by mundschenk-at** [comment]
Any update, @dshanske?

**Comment by dshanske** [comment]
I have been swamped with other problems. I apologise. I will reope in future if needed.
